#! venv/bin/python

"""
            (         (
       (    )\ )      )\ )  (   (      (
 (    ))\  (()/(  (  (()/(  )\  )(    ))\
 )\  /((_)  ((_)) )\  /(_))((_)(()\  /((_)
((_)(_))(   _| | ((_)(_) _| (_) ((_)(_))
(_-<| || |/ _` |/ _ \ |  _| | || '_|/ -_)
/__/ \_,_|\__,_|\___/ |_|   |_||_|  \___|

n vital automation tools and services (nvats)

This project aims to provide a platform and framework for various
command line tools and services to automate a lot of things. The
framework will provide simple APIs for the platform to execute
some task such as communication with both users and OSes, Automating
APIs on OS level etc.

Copyright (C) 2018 Vijaydeep Sharma <vijaydeep@sudofire.com>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Documantation: https://bitbucket.org/sudofire/nvats/wiki/Home
License: https://bitbucket.org/sudofire/nvats/wiki/license.txt
"""

# python imports

# third-party imports

# platform imports
from deck.operations import Operation

# local imports

if __name__ == '__main__': # entry point
    Operation().execute()
