#! venv/bin/python

"""
            (         (
       (    )\ )      )\ )  (   (      (
 (    ))\  (()/(  (  (()/(  )\  )(    ))\
 )\  /((_)  ((_)) )\  /(_))((_)(()\  /((_)
((_)(_))(   _| | ((_)(_) _| (_) ((_)(_))
(_-<| || |/ _` |/ _ \ |  _| | || '_|/ -_)
/__/ \_,_|\__,_|\___/ |_|   |_||_|  \___|

This file provides main entry point for nvats program

Documantation: https://bitbucket.org/sudofire/nvats/wiki/Home

Author: Vijaydeep Sharma <vijaydeep@sudofire.com>
"""

from platform.io.input import Prompt

def main():
    args = Prompt().parse()

if __name__ == '__main__':
    main()
