#! venv/bin/python

"""
            (         (
       (    )\ )      )\ )  (   (      (
 (    ))\  (()/(  (  (()/(  )\  )(    ))\
 )\  /((_)  ((_)) )\  /(_))((_)(()\  /((_)
((_)(_))(   _| | ((_)(_) _| (_) ((_)(_))
(_-<| || |/ _` |/ _ \ |  _| | || '_|/ -_)
/__/ \_,_|\__,_|\___/ |_|   |_||_|  \___|

This file provides main entry point for nvats program

Documantation: https://bitbucket.org/sudofire/nvats/wiki/Home

Author: Vijaydeep Sharma <vijaydeep@sudofire.com>
"""

# python imports

# third-party imports

# platform imports
from platform.operations import Operation

# local imports

if __name__ == '__main__':
    Operation().execute()
